name: CustomWallet
version: '1.2'
main: pl.danielo535.customwallet.CustomWallet
api-version: '1.13'
authors: [danielo535]
description: Plugin for custom money
softdepend: [PlaceholderAPI]

commands:
  wallet:
    aliases: custom-wallet
